### ISSUE TITLE
Doesn't work in Chrome with file protocol

### ISSUE THREAD

**Issue by Jolly-Pirate** [webpgr/cached-webpgr.js#5]
Chrome being a pain as usual, works fine in firefox.
`Access to XMLHttpRequest at 'file:///....../myscript.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`

**Comment by select** [comment]
So is it a request from a (localhost) server to `file://` or from a file URL to a file URL?. 
In general I doubt that with the CORS restrictions in the browser we can do much about it. Let me know how I can reproduce so I can have a look at it and do some research.

**Comment by select** [comment]
Ah well I just read my own readme and it already states that it will now work with file:// URLs , so I already did the research back then and did not find a solution. Sory I guess it just is not something that will work. 

If you feel otherwise and have some additional information I was missing let me know in the issue and I will have a look.
